name: gbai_mlx_lm
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip=24.0
  - pip:
      - mlx>=0.25.0
      - transformers[sentencepiece]>=4.39.3
      - huggingface_hub
      - fastapi
      - uvicorn
      - pydantic