name: gbai_mlx_lm
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - pip=24.0
  - pytorch::pytorch>=2.0
  - pip:
      - mlx>=0.22.0
      - numpy
      - protobuf
      - torch>=2.0.0
      - sentencepiece
      - huggingface_hub
      - transformers>=4.39.3
      - pyyaml
      - jinja2
      - fastapi
      - uvicorn
      - pydantic
